### ISSUE TITLE
서울 지하철 개선 시스템 

### ISSUE THREAD

**Issue by DBrider3** [OSS-GodKiwoonForever/Final-Project#3]
주제 : 지하철 칸 별로 인원현황이 어떻게 되는지 시스템 적용(오픈소스 찾는중…)
현재 지하철을 타봤을때 보통 계단쪽 지하철 칸 에만 사람이 몰리는 경향이 있어서 칸별로  인원현황 시스템을 도입해 사람들이 인원 현황을 보고 적절하게 시민들이 지하철 칸을 선택해 탈 수있게 하여 시민들의 편리성을 높이는 시스템을 만들기
→ 엘레베이터 처럼 각 열차마다 무게센서를 이용해 일정 무게가 넘거나 적정수준이면 사람이 많다 적다를 판단하면 되지않을까요?..?

추가 2018.11.25
출처 : http://www.etnews.com/20180910000169

호주 시드니 지하철은 센서 기술과 빅데이터 분석을 바탕으로 하여 혼잡도를 객차별로 여유, 보통, 혼잡으로 구분하고 모바일 애플리케이션(앱)을 통해서 제공한다.

이를 통해 실시간으로 혼잡하지 않은 쾌적 경로를 안내해 출퇴근 시간대 교통량을 분산시키고 지하철은 고통이 아니라 휴식과 위로를 경험하는 공간이 될 것이다.

**Comment by wngh0908** [comment]
인원현황 파악은  카메라로 얼굴 인식이 아니라 디바이스로?
그냥 온도에 따라 에어컨이 자동으로 나오는 시스템이 더 간단하지 않아?
인원 파악까지 하고 에어컨트려면 일단은 너무 고급기술 같음
구체적으로 어떤 관련 오픈소스가 있는지도 언급해주었으면 하는 아쉬움
★★

**Comment by parksh5061** [comment]
온도조절하는 그 시스템이 오픈소스인지 확인해 볼 필요가 있을것같음!
아이디어는 괜찮은듯 구현이 문제지 ㅜㅠ
★★★

**Comment by keunhyeongkim** [comment]
확실히 버스같은경우에는 승/하차 태그로 인원수 계산이 가능하니까 그걸 이용하면 되긴 한데(현재 버스 남은 좌석 카운팅에 사용중, 여유 혼잡 등등으로 좌석상태 표시)
지하철경우에는 사람 수를 체크하는게 힘들것같네요.. 문에 센서를 달아놓는다고 해도 여러명 한꺼번에 왔다갔다하면 제대로 카운팅도 안되고..
한다고 하면 온도검출기가 한곳에만 있으면 위치별 편차가 있으니까 한 호차 내 좀 여러군데 설치해서 불쾌지수 낮은 온도로 설정하게 하면 좋을것 같네요.
★★★

**Comment by wanderinguser3** [comment]
아이디어는 엄청 참신하네요...! 위에서도 말했듯이 실현 가능성이 발목을 잡을듯 하네요. 
★★★

**Comment by DBrider3** [comment]
>           확실히 버스같은경우에는 승/하차 태그로 인원수 계산이 가능하니까 그걸 이용하면 되긴 한데(현재 버스 남은 좌석 카운팅에 사용중, 여유 혼잡 등등으로 좌석상태 표시)
> 지하철경우에는 사람 수를 체크하는게 힘들것같네요.. 문에 센서를 달아놓는다고 해도 여러명 한꺼번에 왔다갔다하면 제대로 카운팅도 안되고..
> 한다고 하면 온도검출기가 한곳에만 있으면 위치별 편차가 있으니까 한 호차 내 좀 여러군데 설치해서 불쾌지수 낮은 온도로 설정하게 하면 좋을것 같네요.
> ★★★

commet를 보니 저도 온도센서만으로는 인원을 측정하기에는 무리가 있다고 생각이 드네요! 먼가 장치를 늘리는 측면은 단순한 문제가 아니라서 pass.. 다른방법을 생각을 해보겠습니다.

**Comment by dlwpgns0** [comment]
마치 지하 주차장에 자동차가 얼마나 주차되어있는지 표시하는 것과 유사한 아이디어군요.
매우 유용하고 실용적인 아이디어인 것 같습니다. 하지만 소프트웨어만으로 구현하기 힘들것 같네요   ##ㅠㅠ.
★★★
