### ISSUE TITLE
Python을 이용한 오픈소스 게임 만들기

### ISSUE THREAD

**Issue by wanderinguser3** [OSS-GodKiwoonForever/Final-Project#4]
Python을 이용해서 오픈소스 게임 만들기 주제를 제안합니다. 왜냐하면 게임이라는 주제가 가볍고 무시당할 수 있지만 아무래도 Python이라는 (매우) 대중적인 언어를 가지고 하기 때문에 난이도가 상대적으로 쉬울 것이라 예상하고, 인터넷 상에 존재하는 종류, 소스코드도 매우 방대합니다.  예를 들어서 Snake Game, Shooting Game등이 있습니다. 게임 유닛을 추가하거나, 모드 추가, UI 개선 모두 오픈소스에서의 코드 수정 취지에 맞는 것 같습니다. Git에 Python-game이란 주제가 있습니다.

**Comment by wngh0908** [comment]
링크도 올려주세욤
난 일단 주제가 뭐랄까 너무 가볍지 않나 싶어서 다른 팀들에게 호응을 살 수 있을까 싶음
★★

**Comment by parksh5061** [comment]
게임은 발표 때 직접 시연해주면서 보여줘야 호응있을것같은데
깃허브로만 발표하라고 하셔서.. 
만약 발표때 보여줄 기회가 있다면 나쁘지않은듯!
★★★

**Comment by keunhyeongkim** [comment]
게임 만들수있음 발표때 이미지만 짧게 보여주고
게임 링크 던져주면 호응은 좀 이끌어낼수있지않을까
음..그건 안되려나.... 쨌든 보여줄수만 있다면 흥미 이끌어낼수있어서 좋을듯!
★★★

**Comment by DBrider3** [comment]
오픈소스를 이용해 게임을 만든다는것은 교안에도 나와있는것처럼 정말 좋은 프로젝트 같으나 요새는 게임이 단순하면서 인기를 끌려면 창의성이 많이 필요한것 같음. 만약 이 주제를 통해 정말 좋은 게임을 만들고 더 나아가 어플로 구현해 인기를 끌면 좋을것같다고 생각함.

단순하면서 참신해야 하는데 구체적인 창의력을 서술해줬으면 좋겠어요~
★★★★

**Comment by dlwpgns0** [comment]
현재 Play 구글에 나오는 모든 게임은 오픈소스로 구성되어 있습니다. 하지만 하나의 게임을 만들기 위해서는 오픈소스를 찾는 것보다 오픈소스를 가지고 활용??하는 부분이 매우 크기 때문에 아주 많은 시간을 투자해야할 것 같네요... 개인적으로 github에 있는 프로젝트를 활용하여 재밌는 게임을 만들고 싶은 생각은 있습니닿ㅎㅎㅎ
★★★
