### ISSUE TITLE
세종카풀

### ISSUE THREAD

**Issue by parksh5061** [OSS-GodKiwoonForever/Final-Project#6]
카풀 오픈소스를 수정해서 학교 이메일로 학생/직원 인증을 받고 목적지나 출발지를 세종대학교로 고정시키고 학생이나 직원분들만 사용할 수 있는 프로그램 만들기
추가할 기능은 학교 이메일을 입력받고 인증 받기,
사용자가 자신의 위치에서 세종대학교로 갈건지 아니면 세종대학교에서 출발할건지 고르는 정도이기때문에 비교적 어렵지 않게 해낼 수 있을 것  같음

https://github.com/wengwenjun/Carpool

**Comment by wngh0908** [comment]
간단하고 괜찮은 아이디어 굿굿
★★★★

**Comment by keunhyeongkim** [comment]
오오..좋다
진짜 생겨서 썼으면 좋겠당
★★★★

**Comment by wanderinguser3** [comment]
수정이 용이하네요!
★★★★

**Comment by DBrider3** [comment]
간단하고 먼가 학교를 인증하기에 안전하고 주로 차를 가지는 분들이 교수님들이거나 교직원분들이니 학생들과 친해질거같음 하지만 단점은 주로 차를 가지는 분들이 학생은 많이 없기에 카풀을 제공하는 사람들은 세종대 뿐 아니라 서울 대학교로 확대하면 어떨까 아무래도 차를 가지는 사람이 많이 없기에..뚜벅뚜벅
★★★★

**Comment by dlwpgns0** [comment]
매우 좋은 아이디어인 것 같습니다. 카풀 시스템을 도입하여 많은 카풀을 이용할 경우( 제공자) 학교에서 특혜를 준다거나 이런 부분까지 확장시킬 수 있을 것 같습니다.
 들어보니 학교 주차장 요금이 장난아니더라구요... 이것을 통해 많은 불편함을 해소할 수 있는 주제라고 생각합니다.
★★★★★

**Comment by parksh5061** [comment]
> 간단하고 먼가 학교를 인증하기에 안전하고 주로 차를 가지는 분들이 교수님들이거나 교직원분들이니 학생들과 친해질거같음 하지만 단점은 주로 차를 가지는 분들이 학생은 많이 없기에 카풀을 제공하는 사람들은 세종대 뿐 아니라 서울 대학교로 확대하면 어떨까 아무래도 차를 가지는 사람이 많이 없기에..뚜벅뚜벅
> ★★★★

그럼 서울 내 대학들을 목록화해서 대학 간 이동할 수 있는 카풀로 하는것도 괜찮을것같다

**Comment by parksh5061** [comment]
> 매우 좋은 아이디어인 것 같습니다. 카풀 시스템을 도입하여 많은 카풀을 이용할 경우( 제공자) 학교에서 특혜를 준다거나 이런 부분까지 확장시킬 수 있을 것 같습니다.
> 들어보니 학교 주차장 요금이 장난아니더라구요... 이것을 통해 많은 불편함을 해소할 수 있는 주제라고 생각합니다.
> ★★★★★

발표 때 주차장 요금과 관련지어서 언급해주는 것도 좋을듯!
