### ISSUE TITLE
출석 체크 시스템 개선

### ISSUE THREAD

**Issue by wngh0908** [OSS-GodKiwoonForever/Final-Project#7]
현재 우리학교 출석 체크 시스템은 강의실 내로 와서 학생 본인이 직접 수동으로 출석 체크를 눌러 인증을 해야 했지만, 학생이 깜빡할 경우! 결석을 하는 일로 기록되어 재 출결 인증이 불가능한 일이 발생할 수 있다.  세종대 학생이라면 누구나 강의실에 들어오면 출첵을 먼저 해야한다는 강박을 떠안고 학교생활을 하고 있을 것이다.

이를 위해 강의실 내의 공유기(?)가 출석체크를 시작하는 시간(08:50~09:05) 출석체크를 30초마다 시도하여 학교가는 날 블루투스만 켜놓는다면 강의실에 도착만할 경우 자동 출첵이된됨
(< --- 이거 구현만 하면 솔직히 우리학교 사람인 이상 박기웅 교수님이나 학생들이나 좋은 주제라고 공감해줄 것임.)

평소 생활: 블루투스와 데이터나 와이파이를 켜놓고 강의실에 도착하자마자 시간을 확인하여 유체킹을 해야함... 유체크를 할 경우, 다른 친구들한테 유체크할 시간됐다고 알려주면서 지냄. <-- 익숙해졌지만 번거로운 일.

개선된 출첵 시스템의 생활 : 학교오는날 블루투스만 켜놓고 다니면 강의실 도착시, 공유기에서 일정범위 내에 접속된 디바이스에 대하여 자동 출첵을 하며, 사용자에게 출첵이 됐다는 알람이 감 <--보다 편한 학교생활 가능

Ucheck system 이 오픈소스로 공개되어있나?  : No!

![image](https://user-images.githubusercontent.com/38426656/48967236-c89aad80-f020-11e8-858f-daca541ed4d5.png)
![image](https://user-images.githubusercontent.com/38426656/48967238-ce908e80-f020-11e8-91ca-52caadd4f4b4.png)

그럼 오픈소스로 나와있는 출석체크 시스템 중 블루투스를 통한 자동 출석체크 시스템이 구현되어 있지 않는 오픈소스에 자동 출석체크 기능을 추가하여보자!

필요한 오픈소스
 : 1. 기본적인 출첵 시스템 (지금 우리 출첵시스템은 오픈소스 아니겠지? 한번 찾아봄, 아닐 경우 일단 구현 되어있는 기본 출첵 시스템 찾아봄(올라와있는거 있긴 있었음.))
   2. 공유기가 자동적으로 출첵할 시간에 블루투스 존재 유무 체크 (공유기 소스코드 변경)
   3. 블루투스 켜져만 있는 디바이스들 자동 체크 () 
![image](https://user-images.githubusercontent.com/38426656/48967495-9d19c200-f024-11e8-9b3a-8b9c911ebd1b.png)

일단 오픈소스들은 많이 보임

**Comment by keunhyeongkim** [comment]
이거 주제 되게 괜찮은것같아요!
저도 한번 출첵 까먹고 교수님한테 정정요청드렸는데 교수님이 잘못처리해서 처리는 완료됐는데 결석인 상황이라 또 바꿔야해서ㅠㅠ... 
실제 Ucheck에 적용이 된다면 참 좋겠지만 음 개발회사가 할지는 모르겠고.. 호응은 좋을것같아요!
★★★★★

**Comment by wanderinguser3** [comment]
공감대도 형성되고 자료도 많긴 한데 구현 난이도가 좀 될거같네요. 저도 실현이 되면 좋겠네요. 자주 놓쳐서
★★★★

**Comment by wngh0908** [comment]
> 학생들이 강의실오기도 바쁜데 까먹고 유체크를 안한다는건 정말 최악임 그런부분에 대해 속시원하게 개선하는 오픈소스를 활용한 주제라고 생각하지만 학교강의실 내 장치가 30초마다 일일이 블루투스 유무와 학생들이 그 수업을 듣는지 찾는건 아무래도 손실되는 데이터가 많고 장치부터 어플까지 싹 바꿔야 하구 네트워크 (블루투스부분)에 대해 잘알고 있어야 하는데 단기 프로젝트로 하기엔 너무 많은 것을 요구한다고 생각함.
> ★★

구현 난이도 높은 건 인정, 30초마다가 아니라 사실 MHz라 초당 수천번 확인가능함ㅎㅎ;

**Comment by dlwpgns0** [comment]
아이디어 자체만 봤을 때는 저희가 낸 것중 원탑이라고 생각이 듭니다. 하지만 후기를 보니 어플, 서버 상 문제도 매우 많고 건드려야 할 부분이 한두가지가 아닐꺼 같단 생각이 듭니다.
 개인적으로 이 프로젝트 진행해보는 것도 나쁘지 않을꺼 같아요!!
★★★
