### ISSUE TITLE
Chaskey를 이용한 임베디드 시스템의 보안성 UP!

### ISSUE THREAD

**Issue by dlwpgns0** [OSS-GodKiwoonForever/Final-Project#9]
현재 사물 인터넷은 매우 중요한 위치에 있습니다. 사물 인터넷을 통해 삶의 질을 더욱더 윤택하게 할 수 있지만 사실상 흔히 볼 수 있는 임베디드들의 보안성은 매우 취약합니다. 왜냐하면 한정된 자원속에서 보안성을 추구하기엔 너무나도 많은 돈이 들기에 사실상 해킹하기 쉬운편입니다.

 Chaskey 라는 경량화 암호 알고리즘을 사용하여 임베디드에 집어넣어 조금이라도 보안성을 높이는 방안을 생각해보았습니다. 
 Chaskey : https://github.com/lee170116/chaskey

현재 보안 프로그래밍이라는 과목에서 이것을 주제로 하여 프로젝트를 진행할 계획이기에 한번 주제를 연관시켜보았습니다.

**Comment by wngh0908** [comment]
만약 이걸로 발표한다면 임베디드 시스템에다가 설정해서 보여줄 순 없겠지??
그럼 아무 임베디드 소스코드(적합한) 가져와서 거기다가 할 건가?
일단 우리 자유 주제지만 전공 연계성이 있으면 좋긴할거니까 호의적이지 않을 수가 없네
★★★★

**Comment by dlwpgns0** [comment]
>           만약 이걸로 발표한다면 임베디드 시스템에다가 설정해서 보여줄 순 없겠지??
> 그럼 아무 임베디드 소스코드(적합한) 가져와서 거기다가 할 건가?
> 일단 우리 자유 주제지만 전공 연계성이 있으면 좋긴할거니까 호의적이지 않을 수가 없네
> ★★★★

먼저 보안 프로그래밍에서 진행하는 프로젝트에서는 보편적으로 사용되는 임베디드 기기의 성능을 가진  임베디드를 통해서 시현할 생각입니다.  기존에 있는 암호화 알고리즘들은 임베디드 시스템에서 돌리기에는 무겁고 돌리기 위해서는 임베디드 기기 자체의 성능을 업그레이드 해야하는데 그건 현실적인 대안이   아니기 때문에 Chaskey라는 알고리즘을 이용하여 한층더 보안을 업그레이드 한다는 생각을 해봤습니다.

**Comment by DBrider3** [comment]
진행사항은 어느정도야?? 자유주제지만 보안에 관련되면 너무 좋을거같은데 보안과 관련된 주제는 아무래도 어려운 부분이 많던데 이건 어느정도인지?? 
★★★★

**Comment by keunhyeongkim** [comment]
전공이랑 관련되어있어서 호응도라던가 여러 면에 있어서 플러스 요인이 많을것 같네요.
시현이 가능한거면 괜찮을것같아요.
★★★★★

**Comment by wanderinguser3** [comment]
전공이랑 관련성이 높아서 좋은 주제 같네요.
★★★★
